/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * LgymApi.Api
 * OpenAPI spec version: 1.0
 */

export interface AdminUserDto {
  /** @nullable */
  id?: string | null;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  avatar?: string | null;
  /** @nullable */
  profileRank?: string | null;
  isVisibleInRanking?: boolean;
  isBlocked?: boolean;
  isDeleted?: boolean;
  createdAt?: string;
  /** @nullable */
  updatedAt?: string | null;
  /** @nullable */
  roles?: string[] | null;
}
