/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * LgymApi.Api
 * OpenAPI spec version: 1.0
 */

export interface AppConfigInfoDto {
  /** @nullable */
  minRequiredVersion?: string | null;
  /** @nullable */
  latestVersion?: string | null;
  forceUpdate?: boolean;
  /** @nullable */
  updateUrl?: string | null;
  /** @nullable */
  releaseNotes?: string | null;
}
