/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * LgymApi.Api
 * OpenAPI spec version: 1.0
 */

export type AppConfigDetailDtoPlatform = typeof AppConfigDetailDtoPlatform[keyof typeof AppConfigDetailDtoPlatform];


export const AppConfigDetailDtoPlatform = {
  Unknown: 'Unknown',
  Android: 'Android',
  Ios: 'Ios',
} as const;
