/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * LgymApi.Api
 * OpenAPI spec version: 1.0
 */

export type AppConfigInfoWithPlatformDtoPlatform = typeof AppConfigInfoWithPlatformDtoPlatform[keyof typeof AppConfigInfoWithPlatformDtoPlatform];


export const AppConfigInfoWithPlatformDtoPlatform = {
  Unknown: 'Unknown',
  Android: 'Android',
  Ios: 'Ios',
} as const;
