/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * LgymApi.Api
 * OpenAPI spec version: 1.0
 */

export type AppConfigVersionRequestDtoPlatform = typeof AppConfigVersionRequestDtoPlatform[keyof typeof AppConfigVersionRequestDtoPlatform];


export const AppConfigVersionRequestDtoPlatform = {
  Unknown: 'Unknown',
  Android: 'Android',
  Ios: 'Ios',
} as const;
