/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * LgymApi.Api
 * OpenAPI spec version: 1.0
 */

export interface CheckOffSupplementIntakeRequest {
  /** @nullable */
  planItemId?: string | null;
  intakeDate?: string;
  /** @nullable */
  takenAt?: string | null;
}
