/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * LgymApi.Api
 * OpenAPI spec version: 1.0
 */

export interface CompletePhotoUploadRequest {
  /** @nullable */
  storageKey?: string | null;
  /** @nullable */
  mimeType?: string | null;
  sizeBytes?: number;
  /** @nullable */
  checksum?: string | null;
  /** @nullable */
  reportRequestId?: string | null;
  /** @nullable */
  viewType?: string | null;
}
