/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * LgymApi.Api
 * OpenAPI spec version: 1.0
 */
import type { CompleteStepRequestStep } from './completeStepRequestStep';
import type { CompleteStepRequestTutorialType } from './completeStepRequestTutorialType';

export interface CompleteStepRequest {
  tutorialType?: CompleteStepRequestTutorialType;
  step?: CompleteStepRequestStep;
}
