/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * LgymApi.Api
 * OpenAPI spec version: 1.0
 */

export type CompleteTutorialRequestTutorialType = typeof CompleteTutorialRequestTutorialType[keyof typeof CompleteTutorialRequestTutorialType];


export const CompleteTutorialRequestTutorialType = {
  Unknown: 'Unknown',
  OnboardingDemo: 'OnboardingDemo',
} as const;
