/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * LgymApi.Api
 * OpenAPI spec version: 1.0
 */

export interface CreateTrainerInvitationByEmailRequest {
  /** @nullable */
  email?: string | null;
  /** @nullable */
  preferredLanguage?: string | null;
  /** @nullable */
  preferredTimeZone?: string | null;
}
