/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * LgymApi.Api
 * OpenAPI spec version: 1.0
 */

export interface DietPlanHistoryDto {
  /** @nullable */
  _id?: string | null;
  /** @nullable */
  dietPlanId?: string | null;
  /** @nullable */
  changedByUserId?: string | null;
  changeDate?: string;
  /** @nullable */
  changeType?: string | null;
  /** @nullable */
  snapshotJson?: string | null;
}
