/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * LgymApi.Api
 * OpenAPI spec version: 1.0
 */
import type { DietMealDto } from './dietMealDto';

export interface DietPlanDto {
  /** @nullable */
  estimatedCalories?: number | null;
  /** @nullable */
  proteinGrams?: number | null;
  /** @nullable */
  carbsGrams?: number | null;
  /** @nullable */
  fatGrams?: number | null;
  /** @nullable */
  name?: string | null;
  startDate?: string;
  /** @nullable */
  endDate?: string | null;
  /** @nullable */
  notes?: string | null;
  isActive?: boolean;
  /** @nullable */
  _id?: string | null;
  /** @nullable */
  trainerId?: string | null;
  /** @nullable */
  traineeId?: string | null;
  createdAt?: string;
  updatedAt?: string;
  /** @nullable */
  meals?: DietMealDto[] | null;
}
