/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * LgymApi.Api
 * OpenAPI spec version: 1.0
 */

export interface DietMealDto {
  /** @nullable */
  estimatedCalories?: number | null;
  /** @nullable */
  proteinGrams?: number | null;
  /** @nullable */
  carbsGrams?: number | null;
  /** @nullable */
  fatGrams?: number | null;
  /** @nullable */
  name?: string | null;
  order?: number;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  _id?: string | null;
}
