/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * LgymApi.Api
 * OpenAPI spec version: 1.0
 */

export interface EnqueueTestPushEventRequest {
  /** @nullable */
  recipientUserId?: string | null;
  /** @nullable */
  type?: string | null;
  /** @nullable */
  eventId?: string | null;
  /** @nullable */
  entityId?: string | null;
  /** @nullable */
  inAppNotificationId?: string | null;
  /** @nullable */
  deeplink?: string | null;
}
