/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * LgymApi.Api
 * OpenAPI spec version: 1.0
 */
import type { ExerciseResponseDto } from './exerciseResponseDto';
import type { ExerciseScoreResponseDto } from './exerciseScoreResponseDto';

export interface EnrichedExerciseDto {
  /** @nullable */
  exerciseScoreId?: string | null;
  /** @nullable */
  scoresDetails?: ExerciseScoreResponseDto[] | null;
  exerciseDetails?: ExerciseResponseDto;
}
