/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * LgymApi.Api
 * OpenAPI spec version: 1.0
 */
import type { EnumLookupDto } from './enumLookupDto';

export interface EnumLookupResponseDto {
  /** @nullable */
  enumType?: string | null;
  /** @nullable */
  values?: EnumLookupDto[] | null;
}
