/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * LgymApi.Api
 * OpenAPI spec version: 1.0
 */
import type { ExerciseByBodyPartRequestDtoBodyPart } from './exerciseByBodyPartRequestDtoBodyPart';

export interface ExerciseByBodyPartRequestDto {
  bodyPart: ExerciseByBodyPartRequestDtoBodyPart;
}
