/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * LgymApi.Api
 * OpenAPI spec version: 1.0
 */
import type { EnumLookupDto } from './enumLookupDto';

export interface ExerciseScoreResponseDto {
  /** @nullable */
  _id?: string | null;
  weight?: number;
  unit?: EnumLookupDto;
  reps?: number;
  /** @nullable */
  exercise?: string | null;
  series?: number;
}
