/**
 * Generated by orval v8.5.3
 * Do not edit manually.
 * LgymApi.Api
 * OpenAPI spec version: 1.0
 */

import type { ExerciseEloFormula } from "./exerciseEloFormula";
import type { ExerciseFormDtoBodyPart } from "./exerciseFormDtoBodyPart";

export interface ExerciseExtendedFormDto {
  /** @nullable */
  _id?: string | null;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  user?: string | null;
  bodyPart?: ExerciseFormDtoBodyPart;
  /** @nullable */
  eloFormula?: ExerciseEloFormula | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  image?: string | null;
}
