/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * LgymApi.Api
 * OpenAPI spec version: 1.0
 */

export interface ExerciseScoresChartDataDto {
  /** @nullable */
  _id?: string | null;
  value?: number;
  /** @nullable */
  date?: string | null;
  /** @nullable */
  exerciseName?: string | null;
  /** @nullable */
  exerciseId?: string | null;
}
