/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * LgymApi.Api
 * OpenAPI spec version: 1.0
 */
import type { SeriesScoreDto } from './seriesScoreDto';

export interface ExerciseTrainingHistoryItemDto {
  /** @nullable */
  _id?: string | null;
  date?: string;
  /** @nullable */
  gymName?: string | null;
  /** @nullable */
  trainingName?: string | null;
  /** @nullable */
  seriesScores?: SeriesScoreDto[] | null;
}
