/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * LgymApi.Api
 * OpenAPI spec version: 1.0
 */
import type { EnumLookupDto } from './enumLookupDto';
import type { LookupItemVm } from './lookupItemVm';

export interface ExerciseResponseDto {
  /** @nullable */
  _id?: string | null;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  user?: string | null;
  bodyPart?: EnumLookupDto;
  eloFormula?: LookupItemVm;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  image?: string | null;
}
