/**
 * Generated by orval v8.5.3
 * Do not edit manually.
 * LgymApi.Api
 * OpenAPI spec version: 1.0
 */

export type ExerciseEloFormula = typeof ExerciseEloFormula[keyof typeof ExerciseEloFormula];

export const ExerciseEloFormula = {
  Standard: "Standard",
  StrengthWeighted: "StrengthWeighted",
  VolumeWeighted: "VolumeWeighted",
  PullupWeighted: "PullupWeighted",
} as const;
