/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * LgymApi.Api
 * OpenAPI spec version: 1.0
 */
import type { ExerciseScoresTrainingFormDtoUnit } from './exerciseScoresTrainingFormDtoUnit';

export interface ExerciseScoresTrainingFormDto {
  /** @nullable */
  _id?: string | null;
  weight?: number;
  unit?: ExerciseScoresTrainingFormDtoUnit;
  reps?: number;
  /** @nullable */
  exercise?: string | null;
  series?: number;
}
