/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * LgymApi.Api
 * OpenAPI spec version: 1.0
 */

export interface ExerciseTranslationDto {
  /** @nullable */
  exerciseId?: string | null;
  /** @nullable */
  culture?: string | null;
  /** @nullable */
  name?: string | null;
}
