/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * LgymApi.Api
 * OpenAPI spec version: 1.0
 */
import type { ExerciseExtendedFormDtoBodyPart } from './exerciseExtendedFormDtoBodyPart';
import type { LookupItemVm } from './lookupItemVm';

export interface ExerciseExtendedFormDto {
  /** @nullable */
  _id?: string | null;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  user?: string | null;
  bodyPart: ExerciseExtendedFormDtoBodyPart;
  eloFormula?: LookupItemVm;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  image?: string | null;
}
