/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * LgymApi.Api
 * OpenAPI spec version: 1.0
 */

export interface ExternalLoginDto {
  /** @nullable */
  provider?: string | null;
  /** @nullable */
  providerEmail?: string | null;
}
