/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * LgymApi.Api
 * OpenAPI spec version: 1.0
 */
import type { FilterCondition } from './filterCondition';
import type { FilterGroupOperator } from './filterGroupOperator';

export interface FilterGroup {
  operator: FilterGroupOperator;
  /** @nullable */
  conditions?: FilterCondition[] | null;
  /** @nullable */
  groups?: FilterGroup[] | null;
}
