/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * LgymApi.Api
 * OpenAPI spec version: 1.0
 */

export type FilterGroupOperator = typeof FilterGroupOperator[keyof typeof FilterGroupOperator];


export const FilterGroupOperator = {
  And: 'And',
  Or: 'Or',
} as const;
