/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * LgymApi.Api
 * OpenAPI spec version: 1.0
 */

export type FilterConditionOperator = typeof FilterConditionOperator[keyof typeof FilterConditionOperator];


export const FilterConditionOperator = {
  Equals: 'Equals',
  NotEquals: 'NotEquals',
  Contains: 'Contains',
  StartsWith: 'StartsWith',
  EndsWith: 'EndsWith',
  In: 'In',
  GreaterThan: 'GreaterThan',
  GreaterThanOrEqual: 'GreaterThanOrEqual',
  LessThan: 'LessThan',
  LessThanOrEqual: 'LessThanOrEqual',
} as const;
