/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * LgymApi.Api
 * OpenAPI spec version: 1.0
 */
import type { FilterConditionOperator } from './filterConditionOperator';

export interface FilterCondition {
  /** @nullable */
  fieldName: string | null;
  operator: FilterConditionOperator;
  value?: unknown | null;
}
