/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * LgymApi.Api
 * OpenAPI spec version: 1.0
 */
import type { GetApiMeasurementsIdTrendBodyPart } from './getApiMeasurementsIdTrendBodyPart';
import type { GetApiMeasurementsIdTrendUnit } from './getApiMeasurementsIdTrendUnit';

export type GetApiMeasurementsIdTrendParams = {
BodyPart?: GetApiMeasurementsIdTrendBodyPart;
Unit?: GetApiMeasurementsIdTrendUnit;
};
