/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * LgymApi.Api
 * OpenAPI spec version: 1.0
 */
import type { GetApiMeasurementsIdGetHistoryBodyPart } from './getApiMeasurementsIdGetHistoryBodyPart';
import type { GetApiMeasurementsIdGetHistoryUnit } from './getApiMeasurementsIdGetHistoryUnit';

export type GetApiMeasurementsIdGetHistoryParams = {
BodyPart?: GetApiMeasurementsIdGetHistoryBodyPart;
Unit?: GetApiMeasurementsIdGetHistoryUnit;
};
