/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * LgymApi.Api
 * OpenAPI spec version: 1.0
 */

export type GetApiMeasurementsIdTrendBodyPart = typeof GetApiMeasurementsIdTrendBodyPart[keyof typeof GetApiMeasurementsIdTrendBodyPart];


export const GetApiMeasurementsIdTrendBodyPart = {
  Unknown: 'Unknown',
  Chest: 'Chest',
  Back: 'Back',
  Shoulders: 'Shoulders',
  Biceps: 'Biceps',
  Triceps: 'Triceps',
  Forearms: 'Forearms',
  Abs: 'Abs',
  Quads: 'Quads',
  Hamstrings: 'Hamstrings',
  Calves: 'Calves',
  Glutes: 'Glutes',
} as const;
