/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * LgymApi.Api
 * OpenAPI spec version: 1.0
 */

export type GetApiTrainerTraineesParams = {
Search?: string;
Status?: string;
SortBy?: string;
SortDirection?: string;
Page?: number;
PageSize?: number;
};
