/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * LgymApi.Api
 * OpenAPI spec version: 1.0
 */
import type { GetApiMeasurementsIdListBodyPart } from './getApiMeasurementsIdListBodyPart';
import type { GetApiMeasurementsIdListUnit } from './getApiMeasurementsIdListUnit';

export type GetApiMeasurementsIdListParams = {
BodyPart?: GetApiMeasurementsIdListBodyPart;
Unit?: GetApiMeasurementsIdListUnit;
};
