/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * LgymApi.Api
 * OpenAPI spec version: 1.0
 */

export type GetApiMeasurementsIdListUnit = typeof GetApiMeasurementsIdListUnit[keyof typeof GetApiMeasurementsIdListUnit];


export const GetApiMeasurementsIdListUnit = {
  Unknown: 'Unknown',
  Meters: 'Meters',
  Centimeters: 'Centimeters',
  Millimeters: 'Millimeters',
} as const;
