/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * LgymApi.Api
 * OpenAPI spec version: 1.0
 */

export type GetApiMeasurementsIdGetHistoryUnit = typeof GetApiMeasurementsIdGetHistoryUnit[keyof typeof GetApiMeasurementsIdGetHistoryUnit];


export const GetApiMeasurementsIdGetHistoryUnit = {
  Unknown: 'Unknown',
  Kilograms: 'Kilograms',
  Pounds: 'Pounds',
  Meters: 'Meters',
  Centimeters: 'Centimeters',
  Millimeters: 'Millimeters',
  Percent: 'Percent',
  Bmi: 'Bmi',
} as const;
