/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * LgymApi.Api
 * OpenAPI spec version: 1.0
 */
import type { SeriesScoreWithGymDto } from './seriesScoreWithGymDto';

export interface LastExerciseScoresResponseDto {
  /** @nullable */
  exerciseId?: string | null;
  /** @nullable */
  exerciseName?: string | null;
  /** @nullable */
  seriesScores?: SeriesScoreWithGymDto[] | null;
}
