/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * LgymApi.Api
 * OpenAPI spec version: 1.0
 */
import type { LastTrainingGymPlanDayInfoDto } from './lastTrainingGymPlanDayInfoDto';

export interface LastTrainingGymInfoDto {
  /** @nullable */
  _id?: string | null;
  createdAt?: string;
  type?: LastTrainingGymPlanDayInfoDto;
  /** @nullable */
  name?: string | null;
}
