/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * LgymApi.Api
 * OpenAPI spec version: 1.0
 */
import type { PlanDayChooseDto } from './planDayChooseDto';

export interface LastTrainingInfoDto {
  /** @nullable */
  _id?: string | null;
  /** @nullable */
  type?: string | null;
  createdAt?: string;
  planDay?: PlanDayChooseDto;
  /** @nullable */
  gym?: string | null;
}
