/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * LgymApi.Api
 * OpenAPI spec version: 1.0
 */
import type { UserInfoDto } from './userInfoDto';

export interface LoginResponseDto {
  /** @nullable */
  token?: string | null;
  req?: UserInfoDto;
  /** @nullable */
  permissionClaims?: string[] | null;
}
