/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * LgymApi.Api
 * OpenAPI spec version: 1.0
 */
import type { EnumLookupDto } from './enumLookupDto';
import type { ExerciseResponseDto } from './exerciseResponseDto';

export interface MainRecordsLastDto {
  /** @nullable */
  _id?: string | null;
  weight?: number;
  date?: string;
  unit?: EnumLookupDto;
  /** @nullable */
  exercise?: string | null;
  exerciseDetails?: ExerciseResponseDto;
}
