/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * LgymApi.Api
 * OpenAPI spec version: 1.0
 */
import type { MainRecordsFormDtoUnit } from './mainRecordsFormDtoUnit';

export interface MainRecordsFormDto {
  /** @nullable */
  _id?: string | null;
  weight: number;
  date: string;
  unit: MainRecordsFormDtoUnit;
  /** @nullable */
  exercise?: string | null;
}
