/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * LgymApi.Api
 * OpenAPI spec version: 1.0
 */

export type MainRecordsFormDtoUnit = typeof MainRecordsFormDtoUnit[keyof typeof MainRecordsFormDtoUnit];


export const MainRecordsFormDtoUnit = {
  Unknown: 'Unknown',
  Kilograms: 'Kilograms',
  Pounds: 'Pounds',
} as const;
