/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * LgymApi.Api
 * OpenAPI spec version: 1.0
 */
import type { MeasurementFormDtoBodyPart } from './measurementFormDtoBodyPart';
import type { MeasurementFormDtoUnit } from './measurementFormDtoUnit';

export interface MeasurementFormDto {
  /** @nullable */
  user?: string | null;
  bodyPart: MeasurementFormDtoBodyPart;
  unit: MeasurementFormDtoUnit;
  value: number;
  /** @nullable */
  createdAt?: string | null;
  /** @nullable */
  updatedAt?: string | null;
}
