/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * LgymApi.Api
 * OpenAPI spec version: 1.0
 */
import type { EnumLookupDto } from './enumLookupDto';

export interface MeasurementTrendDto {
  bodyPart?: EnumLookupDto;
  unit?: EnumLookupDto;
  startValue?: number;
  currentValue?: number;
  change?: number;
  changePercentage?: number;
  /** @nullable */
  direction?: string | null;
  points?: number;
}
