/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * LgymApi.Api
 * OpenAPI spec version: 1.0
 */
import type { InAppNotificationResultDto } from './inAppNotificationResultDto';

export interface PagedNotificationsResultDto {
  /** @nullable */
  items?: InAppNotificationResultDto[] | null;
  hasNextPage?: boolean;
  /** @nullable */
  nextCursorCreatedAt?: string | null;
  /** @nullable */
  nextCursorId?: string | null;
}
