/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * LgymApi.Api
 * OpenAPI spec version: 1.0
 */
import type { FilterGroup } from './filterGroup';
import type { SortDescriptor } from './sortDescriptor';

export interface PaginatedRoleRequest {
  page?: number;
  pageSize?: number;
  /** @nullable */
  filterGroups?: FilterGroup[] | null;
  /** @nullable */
  sortDescriptors?: SortDescriptor[] | null;
}
