/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * LgymApi.Api
 * OpenAPI spec version: 1.0
 */
import type { TrainerInvitationDto } from './trainerInvitationDto';

export interface PaginatedTrainerInvitationResult {
  /** @nullable */
  items?: TrainerInvitationDto[] | null;
  page?: number;
  pageSize?: number;
  totalCount?: number;
  totalPages?: number;
  hasNextPage?: boolean;
  hasPreviousPage?: boolean;
}
