/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * LgymApi.Api
 * OpenAPI spec version: 1.0
 */

export interface PermissionClaimLookupDto {
  /** @nullable */
  claimType?: string | null;
  /** @nullable */
  claimValue?: string | null;
  /** @nullable */
  displayName?: string | null;
}
