/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * LgymApi.Api
 * OpenAPI spec version: 1.0
 */

export interface PhotoHistoryItemResponse {
  /** @nullable */
  _id?: string | null;
  /** @nullable */
  storageKey?: string | null;
  /** @nullable */
  viewType?: string | null;
  sizeBytes?: number;
  /** @nullable */
  thumbnailUrl?: string | null;
  /** @nullable */
  readUrl?: string | null;
  /** @nullable */
  reportRequestId?: string | null;
  uploadedAt?: string;
}
