/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * LgymApi.Api
 * OpenAPI spec version: 1.0
 */
import type { ExerciseResponseDto } from './exerciseResponseDto';

export interface PlanDayExerciseVmDto {
  series?: number;
  /** @nullable */
  reps?: string | null;
  exercise?: ExerciseResponseDto;
}
