/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * LgymApi.Api
 * OpenAPI spec version: 1.0
 */
import type { PlanDayExerciseInputDto } from './planDayExerciseInputDto';

export interface PlanDayFormDto {
  /** @nullable */
  _id?: string | null;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  exercises?: PlanDayExerciseInputDto[] | null;
}
