/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * LgymApi.Api
 * OpenAPI spec version: 1.0
 */

export interface PlanDto {
  /** @nullable */
  id?: string | null;
  /** @nullable */
  name?: string | null;
  isActive?: boolean;
  /** @nullable */
  userId?: string | null;
}
