/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * LgymApi.Api
 * OpenAPI spec version: 1.0
 */

export interface PlanDayExerciseInputDto {
  series?: number;
  /** @nullable */
  reps?: string | null;
  /** @nullable */
  exercise?: string | null;
}
