/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * LgymApi.Api
 * OpenAPI spec version: 1.0
 */
import type { RecurringReportAssignmentDtoIntervalUnit } from './recurringReportAssignmentDtoIntervalUnit';
import type { ReportRequestDto } from './reportRequestDto';
import type { ReportTemplateDto } from './reportTemplateDto';

export interface RecurringReportAssignmentDto {
  /** @nullable */
  _id?: string | null;
  /** @nullable */
  trainerId?: string | null;
  /** @nullable */
  traineeId?: string | null;
  /** @nullable */
  templateId?: string | null;
  intervalValue?: number;
  intervalUnit?: RecurringReportAssignmentDtoIntervalUnit;
  startsAt?: string;
  /** @nullable */
  endsAt?: string | null;
  isActive?: boolean;
  /** @nullable */
  note?: string | null;
  /** @nullable */
  currentReportRequestId?: string | null;
  /** @nullable */
  lastRequestCreatedAt?: string | null;
  /** @nullable */
  nextEligibleAt?: string | null;
  createdAt?: string;
  template?: ReportTemplateDto;
  currentReportRequest?: ReportRequestDto;
}
