/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * LgymApi.Api
 * OpenAPI spec version: 1.0
 */

export type RecurringReportAssignmentDtoIntervalUnit = typeof RecurringReportAssignmentDtoIntervalUnit[keyof typeof RecurringReportAssignmentDtoIntervalUnit];


export const RecurringReportAssignmentDtoIntervalUnit = {
  Day: 'Day',
  Week: 'Week',
  Month: 'Month',
} as const;
