/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * LgymApi.Api
 * OpenAPI spec version: 1.0
 */

export type ReportTemplateFieldDtoType = typeof ReportTemplateFieldDtoType[keyof typeof ReportTemplateFieldDtoType];


export const ReportTemplateFieldDtoType = {
  Text: 'Text',
  Number: 'Number',
  Boolean: 'Boolean',
  Date: 'Date',
} as const;
