/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * LgymApi.Api
 * OpenAPI spec version: 1.0
 */
import type { ReportRequestDto } from './reportRequestDto';
import type { ReportSubmissionDtoAnswers } from './reportSubmissionDtoAnswers';

export interface ReportSubmissionDto {
  /** @nullable */
  _id?: string | null;
  /** @nullable */
  reportRequestId?: string | null;
  /** @nullable */
  traineeId?: string | null;
  submittedAt?: string;
  /** @nullable */
  answers?: ReportSubmissionDtoAnswers;
  request?: ReportRequestDto;
}
