/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * LgymApi.Api
 * OpenAPI spec version: 1.0
 */
import type { ReportTemplateFieldRequestType } from './reportTemplateFieldRequestType';

export interface ReportTemplateFieldRequest {
  /** @nullable */
  key?: string | null;
  /** @nullable */
  label?: string | null;
  type?: ReportTemplateFieldRequestType;
  isRequired?: boolean;
  order?: number;
}
