/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * LgymApi.Api
 * OpenAPI spec version: 1.0
 */

export type ReportRequestDtoStatus = typeof ReportRequestDtoStatus[keyof typeof ReportRequestDtoStatus];


export const ReportRequestDtoStatus = {
  Pending: 'Pending',
  Submitted: 'Submitted',
  Cancelled: 'Cancelled',
  Expired: 'Expired',
} as const;
