/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * LgymApi.Api
 * OpenAPI spec version: 1.0
 */
import type { ReportTemplateFieldDto } from './reportTemplateFieldDto';

export interface ReportTemplateDto {
  /** @nullable */
  _id?: string | null;
  /** @nullable */
  trainerId?: string | null;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  description?: string | null;
  createdAt?: string;
  /** @nullable */
  fields?: ReportTemplateFieldDto[] | null;
}
