/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * LgymApi.Api
 * OpenAPI spec version: 1.0
 */

export type ReportTemplateFieldRequestType = typeof ReportTemplateFieldRequestType[keyof typeof ReportTemplateFieldRequestType];


export const ReportTemplateFieldRequestType = {
  Text: 'Text',
  Number: 'Number',
  Boolean: 'Boolean',
  Date: 'Date',
  Photos: 'Photos',
  Measurements: 'Measurements',
} as const;
