/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * LgymApi.Api
 * OpenAPI spec version: 1.0
 */

export interface ResetPasswordRequest {
  /** @nullable */
  token?: string | null;
  /** @nullable */
  newPassword?: string | null;
  /** @nullable */
  confirmPassword?: string | null;
}
