/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * LgymApi.Api
 * OpenAPI spec version: 1.0
 */
import type { EnumLookupDto } from './enumLookupDto';

export interface ScoreDto {
  reps?: number;
  weight?: number;
  unit?: EnumLookupDto;
  /** @nullable */
  _id?: string | null;
}
