/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * LgymApi.Api
 * OpenAPI spec version: 1.0
 */
import type { ScoreWithGymDto } from './scoreWithGymDto';

export interface SeriesScoreWithGymDto {
  series?: number;
  score?: ScoreWithGymDto;
}
