/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * LgymApi.Api
 * OpenAPI spec version: 1.0
 */
import type { SupplementPlanItemDto } from './supplementPlanItemDto';

export interface SupplementPlanDto {
  /** @nullable */
  _id?: string | null;
  /** @nullable */
  trainerId?: string | null;
  /** @nullable */
  traineeId?: string | null;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  notes?: string | null;
  isActive?: boolean;
  createdAt?: string;
  /** @nullable */
  items?: SupplementPlanItemDto[] | null;
}
