/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * LgymApi.Api
 * OpenAPI spec version: 1.0
 */

export interface SupplementComplianceSummaryDto {
  /** @nullable */
  traineeId?: string | null;
  fromDate?: string;
  toDate?: string;
  plannedDoses?: number;
  takenDoses?: number;
  adherenceRate?: number;
}
