/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * LgymApi.Api
 * OpenAPI spec version: 1.0
 */

export interface SupplementScheduleEntryDto {
  /** @nullable */
  planItemId?: string | null;
  /** @nullable */
  supplementName?: string | null;
  /** @nullable */
  dosage?: string | null;
  /** @nullable */
  timeOfDay?: string | null;
  intakeDate?: string;
  taken?: boolean;
  /** @nullable */
  takenAt?: string | null;
}
