/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * LgymApi.Api
 * OpenAPI spec version: 1.0
 */

export interface SupplementPlanItemDto {
  /** @nullable */
  _id?: string | null;
  /** @nullable */
  supplementName?: string | null;
  /** @nullable */
  dosage?: string | null;
  /** @nullable */
  timeOfDay?: string | null;
  daysOfWeekMask?: number;
  order?: number;
}
