/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * LgymApi.Api
 * OpenAPI spec version: 1.0
 */

export type TrainerDashboardTraineeDtoStatus = typeof TrainerDashboardTraineeDtoStatus[keyof typeof TrainerDashboardTraineeDtoStatus];


export const TrainerDashboardTraineeDtoStatus = {
  Linked: 'Linked',
  InvitationPending: 'InvitationPending',
  InvitationExpired: 'InvitationExpired',
  InvitationRejected: 'InvitationRejected',
  InvitationAccepted: 'InvitationAccepted',
  NoRelationship: 'NoRelationship',
} as const;
