/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * LgymApi.Api
 * OpenAPI spec version: 1.0
 */
import type { GroupedExerciseComparisonDto } from './groupedExerciseComparisonDto';
import type { RankDto } from './rankDto';

export interface TrainingSummaryDto {
  /** @nullable */
  comparison?: GroupedExerciseComparisonDto[] | null;
  gainElo?: number;
  userOldElo?: number;
  profileRank?: RankDto;
  nextRank?: RankDto;
  /** @nullable */
  msg?: string | null;
}
