/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * LgymApi.Api
 * OpenAPI spec version: 1.0
 */
import type { ExerciseScoresTrainingFormDto } from './exerciseScoresTrainingFormDto';

export interface TrainingFormDto {
  /** @nullable */
  type?: string | null;
  createdAt: string;
  /** @nullable */
  gym?: string | null;
  /** @nullable */
  exercises?: ExerciseScoresTrainingFormDto[] | null;
}
