/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * LgymApi.Api
 * OpenAPI spec version: 1.0
 */
import type { TrainerDashboardTraineeDto } from './trainerDashboardTraineeDto';

export interface TrainerDashboardTraineesResponse {
  page?: number;
  pageSize?: number;
  total?: number;
  /** @nullable */
  items?: TrainerDashboardTraineeDto[] | null;
}
