/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * LgymApi.Api
 * OpenAPI spec version: 1.0
 */

export interface TraineeNoteDto {
  /** @nullable */
  _id?: string | null;
  /** @nullable */
  trainerId?: string | null;
  /** @nullable */
  traineeId?: string | null;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  content?: string | null;
  visibleToTrainee?: boolean;
  isPinned?: boolean;
  /** @nullable */
  lastUpdatedByUserId?: string | null;
  lastUpdatedAt?: string;
  createdAt?: string;
  updatedAt?: string;
}
