/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * LgymApi.Api
 * OpenAPI spec version: 1.0
 */

export interface TraineeTrainerProfileDto {
  /** @nullable */
  trainerId?: string | null;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  avatar?: string | null;
  linkedAt?: string;
}
