/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * LgymApi.Api
 * OpenAPI spec version: 1.0
 */

export interface TrainerInvitationDto {
  /** @nullable */
  _id?: string | null;
  /** @nullable */
  trainerId?: string | null;
  /** @nullable */
  traineeId?: string | null;
  /** @nullable */
  code?: string | null;
  /** @nullable */
  status?: string | null;
  expiresAt?: string;
  /** @nullable */
  respondedAt?: string | null;
  createdAt?: string;
}
