/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * LgymApi.Api
 * OpenAPI spec version: 1.0
 */
import type { TrainerDashboardTraineeDtoStatus } from './trainerDashboardTraineeDtoStatus';

export interface TrainerDashboardTraineeDto {
  /** @nullable */
  _id?: string | null;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  avatar?: string | null;
  status?: TrainerDashboardTraineeDtoStatus;
  isLinked?: boolean;
  hasPendingInvitation?: boolean;
  hasExpiredInvitation?: boolean;
  /** @nullable */
  linkedAt?: string | null;
  /** @nullable */
  lastInvitationExpiresAt?: string | null;
  /** @nullable */
  lastInvitationRespondedAt?: string | null;
}
