/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * LgymApi.Api
 * OpenAPI spec version: 1.0
 */

export interface UpdateUserRequest {
  /** @nullable */
  name?: string | null;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  profileRank?: string | null;
  isVisibleInRanking?: boolean;
  /** @nullable */
  avatar?: string | null;
}
