/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * LgymApi.Api
 * OpenAPI spec version: 1.0
 */

export type UpdateAppConfigRequestPlatform = typeof UpdateAppConfigRequestPlatform[keyof typeof UpdateAppConfigRequestPlatform];


export const UpdateAppConfigRequestPlatform = {
  Unknown: 'Unknown',
  Android: 'Android',
  Ios: 'Ios',
} as const;
