/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * LgymApi.Api
 * OpenAPI spec version: 1.0
 */

export interface UpsertTraineeNoteRequest {
  /** @nullable */
  title?: string | null;
  /** @nullable */
  content?: string | null;
  visibleToTrainee?: boolean;
  isPinned?: boolean;
}
