/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * LgymApi.Api
 * OpenAPI spec version: 1.0
 */
import type { UpsertDietMealRequest } from './upsertDietMealRequest';

export interface UpsertDietPlanRequest {
  /** @nullable */
  estimatedCalories?: number | null;
  /** @nullable */
  proteinGrams?: number | null;
  /** @nullable */
  carbsGrams?: number | null;
  /** @nullable */
  fatGrams?: number | null;
  /** @nullable */
  name?: string | null;
  startDate?: string;
  /** @nullable */
  endDate?: string | null;
  /** @nullable */
  notes?: string | null;
  isActive?: boolean;
  /** @nullable */
  meals?: UpsertDietMealRequest[] | null;
}
