/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * LgymApi.Api
 * OpenAPI spec version: 1.0
 */
import type { UpsertSupplementPlanItemRequest } from './upsertSupplementPlanItemRequest';

export interface UpsertSupplementPlanRequest {
  /** @nullable */
  name?: string | null;
  /** @nullable */
  notes?: string | null;
  /** @nullable */
  items?: UpsertSupplementPlanItemRequest[] | null;
}
