/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * LgymApi.Api
 * OpenAPI spec version: 1.0
 */

export type UpsertRecurringReportAssignmentRequestIntervalUnit = typeof UpsertRecurringReportAssignmentRequestIntervalUnit[keyof typeof UpsertRecurringReportAssignmentRequestIntervalUnit];


export const UpsertRecurringReportAssignmentRequestIntervalUnit = {
  Day: 'Day',
  Week: 'Week',
  Month: 'Month',
} as const;
