/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * LgymApi.Api
 * OpenAPI spec version: 1.0
 */
import type { UpsertRecurringReportAssignmentRequestIntervalUnit } from './upsertRecurringReportAssignmentRequestIntervalUnit';

export interface UpsertRecurringReportAssignmentRequest {
  /** @nullable */
  templateId?: string | null;
  intervalValue?: number;
  intervalUnit?: UpsertRecurringReportAssignmentRequestIntervalUnit;
  startsAt?: string;
  /** @nullable */
  endsAt?: string | null;
  /** @nullable */
  note?: string | null;
}
