/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * LgymApi.Api
 * OpenAPI spec version: 1.0
 */
import type { RankDto } from './rankDto';

export interface UserInfoDto {
  /** @nullable */
  name?: string | null;
  /** @nullable */
  _id?: string | null;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  avatar?: string | null;
  /** @nullable */
  profileRank?: string | null;
  /** @nullable */
  preferredTimeZone?: string | null;
  createdAt?: string;
  updatedAt?: string;
  elo?: number;
  nextRank?: RankDto;
  isDeleted?: boolean;
  isVisibleInRanking?: boolean;
  /** @nullable */
  roles?: string[] | null;
  /** @nullable */
  permissionClaims?: string[] | null;
  hasActiveTutorials?: boolean;
}
